name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set timezone and Install dependencies
      run: |
        sudo ln -snf /usr/share/zoneinfo/America/Los_Angeles /etc/localtime
        echo America/Los_Angeles > /etc/timezone
        echo 'APT::Install-Suggests "0";' | sudo tee -a /etc/apt/apt.conf.d/00-docker
        echo 'APT::Install-Recommends "0";' | sudo tee -a /etc/apt/apt.conf.d/00-docker
        sudo apt-get update
        sudo apt-get install --no-install-recommends -y git build-essential cmake meson pkg-config libudev-dev libnl-3-dev libnl-route-3-dev python3-dev python3-docutils python3-pyelftools libnuma-dev ca-certificates autoconf libgflags-dev libgflags2.2 libhugetlbfs-dev pciutils libunwind-dev uuid-dev nlohmann-json3-dev
        sudo apt-get --purge -y remove rdma-core librdmacm1 ibverbs-providers libibverbs-dev libibverbs1
        sudo rm -rf /var/lib/apt/lists/*

    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: recursive
        path: 'machnet'

    - name: Build cityhash from source
      run: |
        git clone --depth=1 --recurse-submodules https://github.com/google/cityhash.git
        cd cityhash
        ./configure --enable-sse4.2
        make all check CXXFLAGS="-O3 -msse4.2"

    - name: Build rdma-core
      run: |
        git clone -b 'stable-v40' --single-branch --depth 1 https://github.com/linux-rdma/rdma-core.git rdma-core
        cd rdma-core
        mkdir build
        cd build
        cmake -GNinja -DNO_PYVERBS=1 -DNO_MAN_PAGES=1 ../
        sudo ninja install

    - name: Build DPDK
      run: |
        git clone --depth 1 --branch 'v21.11' https://github.com/DPDK/dpdk.git dpdk
        cd dpdk
        meson build -Dexamples='' -Dplatform=generic -Denable_kmods=false -Dtests=false -Ddisable_drivers='raw/*,crypto/*,baseband/*,dma/*'
        cd build/
        DESTDIR=dpdk/build/install ninja install
        rm -rf dpdk/app dpdk/drivers dpdk/.git dpdk/build/app

    - name: Build Machnet
      run: |
        cd machnet
        mkdir build
        cd build
        CITYHASH_SDK=../cityhash RTE_SDK=../dpdk cmake -DCMAKE_BUILD_TYPE=Release -GNinja ../
        ninja

    - name: CodeQL analysis
      uses: github/codeql-action/analyze@v1
      with:
        languages: cpp
